# Pacotes ####
library(tidyverse)
library(here)
library(tidytext)

# NGRAMS ####
# Tetragrams
tetragrams <- dados |>
  tidytext::unnest_tokens(tetragram, DS_RESUMO, token = "ngrams", n = 4) |>
  tidyr::separate(
    tetragram,
    into = c("word1", "word2", "word3", "word4"),
    sep = " "
  ) |>
  dplyr::count(word1, word2, word3, word4, sort = TRUE) |>
  dplyr::filter(n >= 50) |>
  tidyr::unite(tetragram, word1, word2, word3, word4, sep = " ")

# Salvar arquivo com trigrams
tetragrams |>
  readr::write_csv("01_dados/tetragrams.csv")

# Trigrams
trigrams <- dados |>
  tidytext::unnest_tokens(trigram, DS_RESUMO, token = "ngrams", n = 3) |>
  tidyr::separate(trigram, into = c("word1", "word2", "word3"), sep = " ") |>
  dplyr::count(word1, word2, word3, sort = TRUE) |>
  dplyr::filter(n >= 50) |>
  tidyr::unite(trigram, word1, word2, word3, sep = " ")
# Salvar arquivo com trigrams
trigrams |>
  readr::write_csv("01_dados/trigrams.csv")

# Bigrams
bigrams <- dados |>
  tidytext::unnest_tokens(bigram, DS_RESUMO, token = "ngrams", n = 2) |>
  tidyr::separate(bigram, into = c("word1", "word2"), sep = " ") |>
  dplyr::count(word1, word2, sort = TRUE) |>
  dplyr::filter(n >= 50) |>
  tidyr::unite(bigram, word1, word2, sep = " ")
# Salvar arquivo com bigrams
bigrams |>
  readr::write_csv("01_dados/bigrams.csv")


# DICIONÁRIO DE NGRAMS ####
ngrams <- tibble(
  grams = c(
    # TETRAGRAMS ####
    "programa nacional alimentacao escolar",
    "diabetes mellitus tipo 2",
    "cromatografia liquida alta eficiencia",
    "indice massa corporal idade",
    "guia alimentar populacao brasileira",
    "escala brasileira inseguranca alimentar",
    "teste qui quadrado pearson",
    "acidos graxos cadeia curta",
    "direito humano alimentacao adequada",

    # TRIGRAMS ####
    "indice massa corporal",
    "seguranca alimentar nutricional",
    "doencas cronicas transmissiveis",
    "alimentos in natura",
    "pratica atividade fisica",
    "teste qui quadrado",
    "proteina c reativa",
    "questionario frequencia alimentar",
    "educacao alimentar nutricional",
    "organizacao mundial saude",
    "ensaio clinico randomizado",
    "doenca renal cronica",
    "regressao linear multipla",
    "acidos graxos saturados",
    "hipertensao arterial sistemica",
    "capacidade antioxidante total",
    "aleitamento materno exclusivo",
    "atencao primaria saude",
    "sistema unico saude",
    "programa bolsa familia",
    "recordatorio 24 horas",
    "analise componentes principais",
    "excesso gordura corporal",
    "fatores risco cardiovascular",
    "inseguranca alimentar nutricional",
    "avaliacao consumo alimentar",
    "ganho peso gestacional",
    "densidade mineral ossea",
    "avaliacao subjetiva global",
    "recordatorios 24 horas",
    "forca preensao manual",
    "imc pre gestacional",
    "habitos alimentares saudaveis",
    "ratos wistar machos",
    "lipoproteina baixa densidade",
    "frutas legumes verduras",
    "lipoproteina alta densidade",
    "fatores risco cardiometabolico",
    "baixo peso nascer",
    "especies reativas oxigenio",
    "insatisfacao imagem corporal",
    "relacao cintura quadril",
    "unidades alimentacao nutricao",
    "diabetes tipo 2",
    "unidade terapia intensiva",
    "unidades basicas saude",
    "dieta rica gordura",
    "estrategia saude familia",
    "tecido adiposo branco",
    "vigilancia alimentar nutricional",
    "marcadores estresse oxidativo",
    "teste exato fisher",
    "regressao logistica multinomial",
    "citocinas pro inflamatorias",
    "teor compostos fenolicos",
    "consumo bebidas alcoolicas",
    "menores dois anos",
    "area sob curva",
    "regressao logistica multipla",
    "doenca hepatica gordurosa",
    "gordura corporal total",
    "indice qualidade dieta",
    "sistema nervoso central",
    "solidos soluveis totais",
    "forca preensao palmar",
    "randomizado duplo cego",
    "acoes educacao alimentar",
    "teste t pareado",

    # BIGRAMS ####
    "consumo alimentar",
    "excesso peso",
    "estado nutricional",
    "massa corporal",
    "composicao corporal",
    "estudo transversal",
    "atividade fisica",
    "acidos graxos",
    "consumo alimentos",
    "estresse oxidativo",
    "vitamina d",
    "peso corporal",
    "grupo controle",
    "gordura corporal",
    "fatores risco",
    "qualidade vida",
    "pressao arterial",
    "compostos fenolicos",
    "inseguranca alimentar",
    "estilo vida",
    "fatores associados",
    "doencas cronicas",
    "ganho peso",
    "sexo feminino",
    "tecido adiposo",
    "alimentacao escolar",
    "in natura",
    "ambos sexos",
    "atividade antioxidante",
    "seguranca alimentar",
    "perfil lipidico",
    "alimentacao saudavel",
    "alimentos ultraprocessados",
    "colesterol total",
    "regressao logistica",
    "dieta hiperlipidica",
    "sexo masculino",
    "padroes alimentares",
    "revisao sistematica",
    "covid 19",
    "ingestao alimentar",
    "capacidade antioxidante",
    "circunferencia cintura",
    "compostos bioativos",
    "habitos alimentares",
    "saude publica",
    "qui quadrado",
    "praticas alimentares",
    "regressao linear",
    "perda peso",
    "microbiota intestinal",
    "qualidade dieta",
    "politicas publicas",
    "exercicio fisico",
    "criancas adolescentes",
    "aleitamento materno",
    "doencas cardiovasculares",
    "il 6",
    "massa muscular",
    "risco cardiovascular",
    "percentual gordura",
    "hdl c",
    "resistencia insulina",
    "sindrome metabolica",
    "comportamento alimentar",
    "hipertensao arterial",
    "padrao alimentar",
    "cancer mama",
    "imagem corporal",
    "risco nutricional",
    "pre natal",
    "ensaio clinico",
    "vitamina c",
    "regressao poisson",
    "ambiente alimentar",
    "ratos wistar",
    "medidas antropometricas",
    "profissionais saude",
    "glicemia jejum",
    "peso nascer",
    "baixo peso",
    "il 10",
    "homa ir",
    "pos parto",
    "escolas publicas",
    "mann whitney",
    "frequencia alimentar",
    "alimentacao adequada",
    "renda familiar",
    "risco cardiometabolico",
    "massa gorda",
    "pandemia covid 19",
    "expressao genica",
    "frutas hortalicas",
    "alimentares saudaveis",
    "frequencia consumo",
    "proteina c",
    "alimentos saudaveis",
    "cirurgia bariatrica",
    "promocao saude",
    "c reativa",
    "marcadores inflamatorios",
    "perimetro cintura",
    "ldl c",
    "massa magra",
    "forca muscular",
    "consumo frutas",
    "omega 3",
    "parametros bioquimicos",
    "obesidade abdominal",
    "escolhas alimentares",
    "gasto energetico",
    "cafe manha",
    "dados sociodemograficos",
    "parametros antropometricos",
    "doenca renal",
    "avaliacao antropometrica",
    "agricultura familiar",
    "sintomas depressivos",
    "alimentos processados",
    "avaliacao nutricional",
    "acido urico",
    "idade gestacional",
    "alimentos industrializados",
    "base populacional",
    "angulo fase",
    "grupo intervencao",
    "oleo coco",
    "revisao literatura",
    "capacidade funcional",
    "resposta inflamatoria",
    "desempenho fisico",
    "treinamento fisico",
    "cor pele",
    "saude mental",
    "alimentacao complementar",
    "estudo coorte",
    "composicao nutricional",
    "bebidas alcoolicas",
    "desfechos clinicos",
    "controle glicemico",
    "cromatografia liquida",
    "estudo observacional",
    "gordura visceral",
    "gordura saturada",
    "leite materno",
    "comportamento sedentario",
    "hemoglobina glicada",
    "adultos idosos",
    "indicadores antropometricos",
    "saude familia",
    "adiposidade corporal",
    "tolerancia glicose",
    "antioxidante total",
    "estudo longitudinal",
    "potencial antioxidante",
    "seguranca alimentos",
    "analise sensorial",
    "dados secundarios",
    "musculo esqueletico",
    "fibra alimentar",
    "frequencia cardiaca",
    "sensibilidade insulina",
    "valor nutricional",
    "cha verde",
    "correlacao pearson",
    "escherichia coli",
    "escolaridade materna",
    "transtornos alimentares",
    "hospital universitario",
    "superoxido dismutase",
    "grau processamento",
    "ensaios clinicos",
    "kruskal wallis",
    "estudantes universitarios",
    "leite humano",
    "processo inflamatorio",
    "soro leite",
    "ambiente escolar",
    "sistema nervoso",
    "oleo peixe",
    "analise fatorial",
    "esteatose hepatica",
    "hipovitaminose d",
    "exames bioquimicos",
    "peso gestacional",
    "classificacao nova",
    "composicao quimica",
    "hdl colesterol",
    "ldl colesterol",
    "legumes verduras",
    "azeite oliva",
    "bioimpedancia eletrica",
    "efeitos suplementacao",
    "registro alimentar",
    "bebidas acucaradas",
    "condicoes socioeconomicas",
    "dados socioeconomicos",
    "ingestao dietetica",
    "oleo essencial",
    "perfil nutricional",
    "tratamento obesidade",
    "anti inflamatorio",
    "atividade antimicrobiana",
    "baixa renda",
    "inatividade fisica",
    "indice adiposidade",
    "ingestao calorica",
    "recem nascidos",
    "recordatorios 24",
    "servicos saude",
    "densidade mineral",
    "oleos essenciais",
    "comportamentos alimentares",
    "compulsao alimentar",
    "seres humanos",
    "teste tukey",
    "carotenoides totais",
    "fatores sociodemograficos",
    "obesidade central",
    "pessoas idosas",
    "ingestao alimentos",
    "materno infantil",
    "sintomas ansiedade",
    "terapia intensiva",
    "variaveis socioeconomicas",
    "produtos alimenticios",
    "metabolismo lipidico",
    "restricao proteica",
    "estado civil",
    "producao alimentos",
    "estudo caso",
    "manipuladores alimentos",
    "staphylococcus aureus",
    "trato gastrointestinal",
    "composicao microbiota",
    "consumo energetico",
    "consumo excessivo",
    "expressao genes",
    "leite derivados",
    "niveis plasmaticos",
    "origem animal",
    "consumo calorico",
    "correlacao spearman",
    "ministerio saude",
    "perfil metabolico",
    "raios x",
    "salario minimo",
    "acesso alimentos",
    "amostra probabilistica",
    "belo horizonte",
    "compra alimentos",
    "estado saude",
    "estatisticamente significativa",
    "meta analise",
    "permeabilidade intestinal",
    "pre escolares",
    "salmonella spp",
    "shapiro wilk",
    "tecido hepatico",
    "vitamina b12",
    "acidez titulavel",
    "acoes educacao",
    "alta hospitalar",
    "estatistica descritiva",
    "marcadores bioquimicos",
    "maturacao sexual",
    "acido ascorbico",
    "analises bioquimicas",
    "carne bovina",
    "criterios glim",
    "funcao renal",
    "industria alimentos",
    "circunferencia abdominal",
    "disponibilidade alimentos",
    "gordura abdominal",
    "systematic reviews",
    "venda alimentos",
    "vulnerabilidade social",
    "circunferencia panturrilha",
    "citocinas pro",
    "delineamento transversal",
    "fatores socioeconomicos",
    "grupos focais",
    "literatura cientifica",
    "salarios minimos",
    "saude intestinal",
    "acompanhamento nutricional",
    "insatisfacao imagem",
    "pre operatorio",
    "recordatorio alimentar",
    "diagnostico desnutricao",
    "estudo intervencao",
    "glutationa peroxidase",
    "ingredientes culinarios",
    "insatisfacao corporal",
    "pacientes adultos",
    "perfil bioquimico",
    "servicos alimentacao",
    "transtornos mentais",
    "balanco energetico",
    "caracteristicas sensoriais",
    "dieta hipoproteica",
    "ingestao energetica",
    "populacao idosa",
    "questionario semiestruturado",
    "recem nascido",
    "disturbios metabolicos",
    "estado inflamatorio",
    "interleucina 6",
    "meio ambiente",
    "nutricao enteral",
    "pacientes criticos",
    "tempo tela",
    "validacao conteudo",
    "alimentos organicos",
    "entrevistas semiestruturadas",
    "estatisticamente significativas",
    "necrose tumoral",
    "pos colheita",
    "restricao calorica",
    "vigilancia sanitaria",
    "controle peso",
    "desenvolvimento infantil",
    "educacao saude",
    "expressao proteica",
    "gordura total",
    "marcadores estresse",
    "pais responsaveis",
    "tecidos adiposos",
    "treinamento forca",
    "anti inflamatorias",
    "atencao saude",
    "calorimetria indireta",
    "camundongos swiss",
    "dieta cetogenica",
    "dobras cutaneas",
    "inflamacao cronica",
    "massa ossea",
    "testes t",
    "zona urbana",
    "acesso alimentacao",
    "circunferencia braco",
    "habito alimentar",
    "indices antropometricos",
    "ingestao diaria",
    "nivel escolaridade",
    "obesidade sarcopenica",
    "padrao consumo",
    "poli insaturados",
    "suplementacao vitamina",
    "analise documental",
    "desmame precoce",
    "doenca cardiovascular",
    "informacao nutricional",
    "ingestao proteica",
    "intervencoes nutricionais",
    "obesidade infantil",
    "primeira infancia",
    "amido resistente",
    "camundongos c57bl",
    "exercicios fisicos",
    "fibras alimentares",
    "ingestao energia",
    "metabolismo glicose",
    "obesidade grave",
    "perfil inflamatorio",
    "revisoes sistematicas",
    "sintomas depressao",
    "suplementacao oleo",
    "amostra representativa",
    "anti inflamatorios",
    "habilidades culinarias",
    "higienico sanitarias",
    "ingestao calcio",
    "internacao hospitalar",
    "ldl colesterol",
    "qualidade microbiologica",
    "terapia interdisciplinar",
    "vida prateleira",
    "alimentos regionais",
    "baixa ingestao",
    "citocinas inflamatorias",
    "dados demograficos",
    "estudo experimental",
    "fatores ambientais",
    "itens alimentares",
    "metabolismo energetico",
    "qualidade muscular",
    "abordagem quantitativa",
    "adiposidade abdominal",
    "cuidado nutricional",
    "indice glicemico",
    "ingestao nutrientes",
    "pacientes idosos",
    "saude ossea",
    "aditivos alimentares",
    "agricultores familiares",
    "baixa escolaridade",
    "classe economica",
    "coliformes totais",
    "dieta materna",
    "equacoes preditivas",
    "exposicao solar",
    "idosos institucionalizados",
    "indice tyg",
    "insulina homa",
    "listeria monocytogenes",
    "marcadores alimentacao",
    "caracteristicas nutricionais",
    "caso controle",
    "estudo clinico",
    "gordura trans",
    "impedancia bioeletrica",
    "suco uva",
    "transversal analitico",
    "triagem nutricional",
    "variancia robusta",
    "via oral",
    "25 hidroxivitamina",
    "apoio social",
    "estudos epidemiologicos",
    "informacoes sociodemograficas",
    "l monocytogenes",
    "lactobacillus acidophilus",
    "oleo chia"
  )
)

ngrams <- ngrams |>
  mutate(n_palavra = str_count(grams, " ") + 1) |>
  arrange(desc(n_palavra))


# Salvar dicionário de ngrams
ngrams |>
  readr::write_csv("01_dados/nutrigrams.csv")
